### ISSUE TITLE
Zabbix LXC script error

### ISSUE THREAD

**Issue by Fragment7436** [community-scripts/ProxmoxVE#1063] opened 2024-12-28 13:42 UTC
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Zabbix LXC

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/zabbix.sh)"

### 📝 Provide a clear and concise description of the issue.

Script returns an error when running the "Setting up PostgreSQL" step and stops the script.

gzip: /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz: No such file or directory
[ERROR] in line 42: exit code 0: while executing command sudo -u $DB_USER psql $DB_NAME &> /dev/null

### ⚙️ What settings are you using?

- [X] Default Settings
- [X] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Script returns same error every time. Tested on three different ProxmoxVEs. Two with default settings and one with advanced settings.

### ❌ Paste the full error output (if available).

No other errors shown in verbose mode other than the below.

gzip: /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz: No such file or directory
[ERROR] in line 42: exit code 0: while executing command sudo -u $DB_USER psql $DB_NAME &> /dev/null

**Comment by MickLesk** [comment] 2024-12-28 14:28
Cant reproduce this.

Can you Check too? @michelroegl-brunner

**Comment by michelroegl-brunner** [comment] 2024-12-28 18:20
![image](https://github.com/user-attachments/assets/dba58b1b-64ce-4567-a0b1-5d8927c7dd7b)
Same error on three of my nodes.

**Comment by MickLesk** [comment] 2024-12-28 18:27
report issue to zabbix.
https://www.zabbix.com/download?zabbix=7.2&os_distribution=debian&os_version=12&components=server_frontend_agent&db=pgsql&ws=apache

the file dont exists in 7.2

**Comment by roswitina** [comment] 2024-12-28 19:12
I get the same error message during installation

```
 ⠼gzip: /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz: No such file or directory

[ERROR] in line 42: exit code 0: while executing command sudo -u $DB_USER psql $DB_NAME &> `/dev/null`

```
The path seems to be wrong. In the Zabbix - LXC container it is

`/usr/share/zabbix/sql-scripts/postgresql/server.sql.gz`

**Comment by MickLesk** [comment] 2024-12-28 19:33
idiots.. ^^ okay, fix in the next 30min

**Comment by MickLesk** [comment] 2024-12-28 19:48
merged

**Closed by MickLesk** 2024-12-28 19:48 UTC
