### ISSUE TITLE
Linkwarden install fails while installing Monolith

### ISSUE THREAD

**Issue by indiependente** [community-scripts/ProxmoxVE#362] opened 2024-11-19 10:41 UTC
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Installation of `linkwarden` fails on `monolith` installation step.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
[ERROR] in line 23: exit code 0: while executing command "$@" > /dev/null 2>&1
The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.
```

### Please provide detailed steps to reproduce the issue.

1. Open node console
2. Paste install command bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/linkwarden.sh)"
3. Press enter to start install process
4. Select Default install
5. It should fail

**Comment by MickLesk** [comment] 2024-11-19 10:55
Work fine for me. Default Settings.
Complete Install Take some time, but it works fine. (~10 Min)

Can you test it with verbose mode? 

<img width="407" alt="image" src="https://github.com/user-attachments/assets/1e631752-8918-4001-b9e1-8ff2048e975a">

**Comment by indiependente** [comment] 2024-11-19 12:12
Sure, here is the output with the verbose mode on:
```
 /  Downloaded 164 crates (22.6 MB) in 2.14s (largest was `openssl-src` at 9.9 MB)
 -error: failed to compile `monolith v2.8.3`, intermediate artifacts can be found at `/tmp/cargo-installLO0dnX`

Caused by:
  package `regex v1.11.1` cannot be built because it requires rustc 1.65 or newer, while the currently active rustc version is 1.63.0
  Try re-running cargo install with `--locked`

[ERROR] in line 41: exit code 0: while executing command $STD cargo install monolith
```

It's an advanced install on Debian 12.

**Comment by MickLesk** [comment] 2024-11-19 12:31
And whats your Advanced Settings?

Do you have an Special DNS ?

Ive try it with advanced Settings, work too

**Comment by indiependente** [comment] 2024-11-19 12:59
The only change is the LXC IP address and the gateway IP address. The DNS it will use is an AdGuard instance running in another LXC pointed at by the gateway but that's the setup every LXC on the node has.

**Comment by MickLesk** [comment] 2024-11-19 13:42
the cargo install failed, i think it cant get some dependencies because dns error. i cant reproduce this.

**Comment by MickLesk** [comment] 2024-11-19 14:13
@Mellowlynx @newzealandpaul @havardthom 



Can any of you reproduce the error? I have specially aligned the LXC against Traefik, CloudflareDNS and Adguard (3 LXC). It works perfectly for me

**Comment by Mellowlynx** [comment] 2024-11-19 16:05
Takes a bit, but runs fine.
```
    __    _       __                           __
   / /   (_)___  / /___      ______ __________/ /__  ____
  / /   / / __ \/ //_/ | /| / / __ `/ ___/ __  / _ \/ __ \
 / /___/ / / / / ,<  | |/ |/ / /_/ / /  / /_/ /  __/ / / /
/_____/_/_/ /_/_/|_| |__/|__/\__,_/_/   \__,_/\___/_/ /_/

Using Default Settings
Using Distribution: ubuntu
Using ubuntu Version: 22.04
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 221
Using Hostname: linkwarden
Using Disk Size: 12GB
Allocated Cores 2
Allocated Ram 2048
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway IP Address: Default
Using Apt-Cacher IP Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Linkwarden LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 221 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 10.0.0.140
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.121.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js/Yarn
 ✓ Installed Monolith
 ✓ Set up PostgreSQL DB
Would you like to add Adminer? <y/N> n
 ✓ Installed Linkwarden
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!
```

**Comment by indiependente** [comment] 2024-11-19 17:13
Tried rerunning. No DNS issues spotted, but maybe the verison of `rustc` is outdated?
```
error: failed to compile `monolith v2.8.3`, intermediate artifacts can be found at `/tmp/cargo-installis2APQ`

Caused by:
  package `tokio-util v0.7.12` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.63.0
  Try re-running cargo install with `--locked`

[ERROR] in line 41: exit code 0: while executing command $STD cargo install monolith
```

**Comment by MickLesk** [comment] 2024-11-19 17:15
Then we would also have the error.

**Comment by indiependente** [comment] 2024-11-19 17:16
Could you please try building it in Debian 12? I think it's a different package version between Debian and Ubuntu.

**Comment by MickLesk** [comment] 2024-11-19 17:30
> Could you please try building it in Debian 12? I think it's a different package version between Debian and Ubuntu.


Default is Debian, i tryed Debian 11,12 and latest ubuntu

**Comment by indiependente** [comment] 2024-11-19 18:03
From the log above and the screenshot you posted I can see the default is Ubuntu 22.04. Now I'm building it using default settings and it's going forward. It's taking a while but it would probably succeed.
So the only real difference I can see on my side it's Debian 12 vs Ubuntu 22.04.
```
    __    _       __                           __
   / /   (_)___  / /___      ______ __________/ /__  ____
  / /   / / __ \/ //_/ | /| / / __ `/ ___/ __  / _ \/ __ \
 / /___/ / / / / ,<  | |/ |/ / /_/ / /  / /_/ /  __/ / / /
/_____/_/_/ /_/_/|_| |__/|__/\__,_/_/   \__,_/\___/_/ /_/

Using Default Settings
Using Distribution: ubuntu
Using ubuntu Version: 22.04
Using Container Type: 1
Using Root Password: Automatic Login
Using Container ID: 136
Using Hostname: linkwarden
Using Disk Size: 12GB
Allocated Cores 2
Allocated Ram 2048
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway IP Address: Default
Using Apt-Cacher IP Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Linkwarden LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 136 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.0.92 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 20.26.156.215
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Set up Node.js Repository
 ✓ Installed Node.js/Yarn
 ✓ Installed Monolith
 ✓ Set up PostgreSQL DB
Would you like to add Adminer? <y/N> y
 ✓ Installed Adminer
 / Installing Linkwarden (Patience) 
```

**Comment by MickLesk** [comment] 2024-11-19 18:31
Right, Default ist Ubuntu, I was thinking about Vaultwarden. 

But it still worked for me. Can only see if it's worth changing it for Debian somehow. But then it's not a bug but a maintenance and will probably be done at some point. So I'll close the issue for now and put it in the backlog.

**Closed** 2024-11-19 18:32 UTC
Labels: question
